name: scanner_personal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  supabase_flutter: ^2.8.4
  record: ^3.0.0
  audioplayers: ^6.4.0
  http: ^1.3.0
  google_fonts: ^6.1.0
  url_launcher: ^6.1.7
  image_picker: ^1.1.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: any
  shared_preferences: ^2.2.2
  bcrypt: ^1.1.3
  logger: ^1.0.0
  flutter_dotenv: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
